### ISSUE TITLE
Alternate color space e.g. LCH

### ISSUE THREAD

**Issue by jfrancos** [Ennoriel/svelte-awesome-color-picker#42]
Hi thanks for making an awesome color picker!

Is there a way to use colord's LCH color-space plugin with svelte-awesome-color-picker?

**Comment by Ennoriel** [comment]
Thanks for your feedback!

What do you exactly want?

Do you want to Access thé LCH values? (You can do that by binding to thé `color` props)

Or would you like to have the slider and picker in terms of LCH standards (which would probably be doable but confusing because very uncomon today and it does not fit in a square (https://lch.oklch.com).

It would be very useful to work with it to select a color palette!
