### ISSUE TITLE
No way to use an empty/optional value

### ISSUE THREAD

**Issue by zetokore** [Ennoriel/svelte-awesome-color-picker#56]
You may want to bind to a value that is optional, but the color picker will convert any empty value to #ff0000, for example, with hex colors.

**Comment by Ennoriel** [comment]
Thanks for opening this issue!

#ff0000 is the default value at the moment. In your proposition, what color should be displayed if no color is provided? And where should be located the pickers when opened?

We also have to think about accessibility here to not confuse people using keyboard navigation or vocal apps.

**Comment by Ennoriel** [comment]
I've thought about this issue for a long time now. Since I am implementing the v3, I was wondering if I could include it in the same time. However, I have some troubles with the implementation.

If there is no color, there is no default value ; hence what color should be set when a user use its keyboard to focus the color picker?

And what would a user do if he wanted to set the color to "undefined"?
