### ISSUE TITLE
iOS native color picker opens up automatically after awesome-color-picker

### ISSUE THREAD

**Issue by djsnipa1** [Ennoriel/svelte-awesome-color-picker#62]
Thank you for this awesome library. I just wanted to point out a bug that I’m encountering…

I’m using Safari on iOS 17.2.1. [Here is a video](https://streamable.com/zkj55l) of the issue I’m facing. It will show that the native iOS color picker opens up immediately after the awesome color picker. That wouldn’t be the worst thing in the world however, if I choose a different color in the iOS picker, the color doesn’t change in the awesome color picker. You will see what I’m talking about. 

If you would like me to try anything, just let me know. Thanks again!

**Comment by Ennoriel** [comment]
Thanks for using the library! 😄 

Are you using the library in v3? This bug came up in v2 (see this issue #18) and I removed the fix to solve accessibility warnings.

Can you check if the problem is solved on this [documentation site preview](https://svelte-awesome-color-picker-32jvreyco-ennoriel.vercel.app/)? I adding again the fix.

**Comment by djsnipa1** [comment]
Oh wow my bad! Yes the examples work perfectly! I feel stupid for pointing this out. I thought I looked through the old issues and I know I did not see I was using the older version.

Thank you again for all your hard work on this and your other open source projects!
