### ISSUE TITLE
Svelte 5 support

### ISSUE THREAD

**Issue by jerrygreen** [Ennoriel/svelte-awesome-color-picker#69]
- [ ] https://github.com/Ennoriel/svelte-awesome-color-picker/issues/68
- [ ] Bindings aren't working as well
  `bind:rgb` or `bind:hsv` etc – only initial values are set, but no any dynamic change after that.

Tested with `svelte@5.0.0-next.67`.

**Comment by Ennoriel** [comment]
The second item has been fixed in the Svelte repo: https://github.com/sveltejs/svelte/pull/11652 and the color picker is now fully working with Svelte 5: [REPL](https://svelte-5-preview.vercel.app/#H4sIAAAAAAAACoWQT0_DMAzFv0pkDgOJrpw4dF0ltBsHNokj4bClzmbR_JGTdZuqfncSECsXxO3Z_vk9JwNo6jBA9TaA3RqECp68h3uIF5-L0GMXMdXBHVnlTh0Uk4-NtDKS8Y6jWLnO8YbUB7LQ7IyYfa8V2xMGZ7BQGSj8FzFb5E1phegwigOexVJIuNGP-qFVEhY_E97vrvoQ-qTrcoq2tWdshufX9cs8RCa7J325TW53Y13m0R9Ecv2HSFkTkZhfj8uH78i2Vcq56uQ49UMvbdmk7zKuJU3YQhX5iOP7-AmEzjcQaQEAAA==).

This issue is now resolved as both items have been adressed!
